### ISSUE TITLE
One-time payment

### ISSUE THREAD

**Issue by Maxhodges** [gratipay/gratipay.com#3368] opened 2015-04-28 13:36 UTC
I'd like to just give some developers a one time payment. if I pay $1 per week to several people, more money is lost to credit card processing fees and also it creates additional work at my organization: the accounts payable team needs to enter the transactions each month in order to reconcile them. One-off is much more efficient. please add it as an option.

Cheers!

**Comment by tshepang** [comment] 2015-04-28 13:56
Dupe of https://github.com/gratipay/gratipay.com/issues/5.

**Comment by rohitpaulk** [comment] 2015-04-28 15:09
Hey @Maxhodges, I see that you've already commented on #5, so I'm closing this.

**Closed by rohitpaulk** 2015-04-28 15:09 UTC
