### ISSUE TITLE
Difference between giving total and giving detail

### ISSUE THREAD

**Issue by timothyfcook** [gratipay/gratipay.com#3570] opened 2015-06-19 15:30 UTC
It says I'm giving $10.25 a week, but I see only see one item for $2.00 in my Subscriptions detail.

Is this an issue with the old recipients of my gifts not having activated/reconciled their accounts with the Gratipay 2.0 restrictions?

![screen shot 2015-06-19 at 11 28 58 am](https://cloud.githubusercontent.com/assets/1823300/8256669/7ddde56e-1676-11e5-9792-cc6106981073.png)

**Comment by whit537** [comment] 2015-06-19 15:33
Dupe of https://github.com/gratipay/gratipay.com/issues/3511!

**Closed by whit537** 2015-06-19 15:33 UTC
