### ISSUE TITLE
Allow closure of 0-balance, unverified accounts

### ISSUE THREAD

**Issue by ribasushi** [gratipay/gratipay.com#3600] opened 2015-07-03 10:07 UTC
This is just a placeholder, requesting ability to close an account once it no longer has a balance (following completion of https://github.com/gratipay/gratipay.com/issues/3587 )

Cheers!

**Comment by whit537** [comment] 2015-07-09 23:01
Thanks @ribasushi. Closing as a duplicate of #3461. Coming soon to a Gratipay near you in #3601 ... ! :-)

**Closed by whit537** 2015-07-09 23:01 UTC
