### ISSUE TITLE
Powered by Gratipay interactive widget for signup and donation

### ISSUE THREAD

**Issue by elliottw** [gratipay/gratipay.com#3676] opened 2015-08-11 04:27 UTC
Have a widget that groups can put on there site, that allows non-gratipay users to easily sign up and donate to that particular group all within their site.

<img width="1035" alt="screen shot 2015-08-11 at 12 23 20 am" src="https://cloud.githubusercontent.com/assets/1633097/9190090/489c472a-3fbf-11e5-932a-b64ef22987e6.png">

I think Gratipay should be as prominent as it can without being annoying, and we can even have a button like "now go explore other projects to support!".

The current thing holding me back from moving a lot of catapultpgh members to gratipay, is that a lot of our base are not developers and I have had to spend 15 minutes onboarding people on to Gratipay to donate, which means lower donation rates not because people don't want to donate, but because they feel they it's very complex and confusing and they are signing up for some big thing when all they want to do is give catapult 10 bucks a months.

**Comment by kzisme** [comment] 2015-08-11 15:05
I was thinking about something like this for a stint of time.  I see a lot of other companies using widgets/buttons on their Twitch streams.  Many other people would be interested if these buttons were introduced and the signup process was streamlined.

**Comment by mattbk** [comment] 2015-08-11 16:30
I like the idea of streamlining the registration/giving process while offsite.

Would it have to wait for https://github.com/gratipay/gratipay.com/issues/1052?

**Comment by whit537** [comment] 2015-08-12 12:33
Closing a dupe of #1167. Will pick up over there ...

**Closed by whit537** 2015-08-12 12:33 UTC
