### ISSUE TITLE
URL Validation doesn't account for +'d emails

### ISSUE THREAD

**Issue by BrettTrotter** [gratipay/gratipay.com#3964] opened 2016-03-14 18:05 UTC
Need to url encode the + to %2b in your validation email links.

**Comment by whit537** [comment] 2016-03-15 02:52
Thanks @BrettTrotter, closing as a dupe of https://github.com/gratipay/gratipay.com/issues/3110, with a +1 for you over there.

**Closed by whit537** 2016-03-15 02:52 UTC
