### ISSUE TITLE
communicate major site changes ... on the site

### ISSUE THREAD

**Issue by colans** [gratipay/gratipay.com#3447] opened 2015-05-15 22:50 UTC
I searched all over the Web UI, but couldn't find a way to cancel a weekly tip/payment I'm making.  Is this not possible?  I would expect there to be a widget on the https://gratipay.com/~$USER/giving/ page allowing me to stop a payment.

**Comment by mattbk** [comment] 2015-05-16 01:36
~~If you go to the page of the person you're tipping, you can edit the amount on the left sidebar.~~

Never mind, that went away.

**Comment by deltab** [comment] 2015-05-16 05:51
Confirmed. As of a few days ago, the widget's been removed and there's no way to create, change, or stop payments. Also, this week's payments were skipped.

It's been removed (in pull request #3406) as part of Gratipay's change in direction, described in "[Gratipocalypse](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8)" on the blog, gratipay/inside.gratipay.com#180, etc.

@whit537, it's rather disconcerting for such a core component of the UI to just vanish, especially one that controls money going out of our bank accounts. Please restore it with suitable changes, or at the very least put in a few words and a link to a longer explanation. That'll save others from trawling through commit logs or raising issues to find out what happened.

**Comment by anselmh** [comment] 2015-05-16 06:46
I’d add a vote for also adding a separate button stating "Cancel this tip" as it’s confusing for users to edit the amount to $0. I received some questions on that topic from some of my donators.
And yes, a statement/notice that currently no payments are processed would also be good. Couldn’t find any on the website.

**Comment by colans** [comment] 2015-05-16 15:24
I opened this ticket because I noticed that folks stopped paying me so I better stop paying others if I want to maintain the equilibrium. It looks like there was no intention behind it. If all payments stopped, then I don't have a problem. 

So yes, the real issue here is that after searching through all of the usual pages, I found no notice or information anywhere on what was actually going on. A short message where these controls normally would be should fix this, with a link to more information.

**Comment by whit537** [comment] 2015-05-17 22:35
Sorry for the confusion, @colans, et al. :-(

I've added +1s to #3432 for turning the tipping/subscription UI back on.

> put in a few words and a link to a longer explanation.
> And yes, a statement/notice that currently no payments are processed would also be good. Couldn’t find any on the website.
> A short message where these controls normally would be should fix this, with a link to more information.

I've PR'd a global site notice in #3452. Is that suitable for now?

**Comment by whit537** [comment] 2015-05-17 22:36
I've rescoped this ticket to be about communicating major site changes on the site itself, since we already have a ticket for bringing back the tipping UI (#3432).

**Comment by whit537** [comment] 2015-05-18 13:22
Closing as I've deployed #3452.

**Closed by whit537** 2015-05-18 13:22 UTC
Labels: ★★★

**Comment by colans** [comment] 2015-05-19 16:12
Perfect.  Thanks.
