### ISSUE TITLE
[Profile page] ConfirmBeforeUnload inappropriate when no change has been done

### ISSUE THREAD

**Issue by slaivyn** [gratipay/gratipay.com#3133] opened 2015-01-23 11:24 UTC
Every time I leave the profile page I have a popup with a message like "This page is asking you to confirm that you want to leave ; you may loose data".
I am used to see this popup on other websites when leaving after having actually modified some editable content or at least after being entered (html "focus") in any textarea/input. But in Gratipay profile page, this check is ever activated which is a bit excessive and annoying.
I think it could be improved adding a check in the callback 'beforeunload.js_edit' in https://github.com/gratipay/gratipay.com/blob/master/js/gratipay/forms.js#L102.
We need a sort of flag at the form level that would be true if something has been modified in the form so the callback could check the flag and apply "e.preventDefault()" only if the flag is true.

**Comment by Changaco** [comment] 2015-01-23 11:40
Closing as duplicate of #3081.

**Closed by Changaco** 2015-01-23 11:40 UTC
