### ISSUE TITLE
Email addresses are inserted unquoted (or at least partially quoted) into confirmation URLs

### ISSUE THREAD

**Issue by Julian** [gratipay/gratipay.com#3141] opened 2015-01-26 18:22 UTC
I've only tried this with my own email address to run into the issue, so I don't know which of the two options in the title it is, but if your email address looks like `Julian+Gratipay@GMail.com`, it's inserted literally into the `email` query string parameter in the confirmation email's link, which then will get unquoted, and the confirmation will fail because it's interpreted as a space. Emails should be quote(`_plus`ed), so that the plus is inserted as `%2B`, which after manual changing, made the confirmation go through.

**Comment by rohitpaulk** [comment] 2015-01-26 18:36
Closing as duplicate of #3110

**Closed by rohitpaulk** 2015-01-26 18:36 UTC

**Comment by Julian** [comment] 2015-01-26 18:37
Ech sorry, thought I checked first. Appreciated.
