### ISSUE TITLE
Removing email from account doesn't seem to work

### ISSUE THREAD

**Issue by ribasushi** [gratipay/gratipay.com#3604] opened 2015-07-08 17:05 UTC
I tried to remove the primary email associated with https://gratipay.com/~ribasushi (so I can reuse it on https://gratipay.com/~dbix-class/ ), and while the `remove` button disappeared, the email is still associated. So I can't reassign it to another account as suggested in https://github.com/gratipay/gratipay.com/issues/3587#issuecomment-117350916

**Comment by stevepiercy** [comment] 2015-07-09 00:30
@ribasushi I have the similar dilemma.

I have a Team account:
https://gratipay.com/~KnopProject/

And an Individual account:
https://gratipay.com/~stevepiercy/

I tried to add my Individual account's primary email address to the Team account, but it was rejected as already being associated with another account. But in my situation, I did not remove my primary email address from the Individual account, pending the outcome of two tickets I submitted via Freshdesk, one for each account, Team and Individual.
https://gratipay.freshdesk.com/support/tickets/2427
https://gratipay.freshdesk.com/support/tickets/2531

I really want to get this resolved so that I can encourage developers to contribute work to the Knop Project.

**Comment by whit537** [comment] 2015-07-10 00:15
@mattbk @rohitpaulk @kzisme @kaguillera Anyone able to reproduce this?

**Comment by stevepiercy** [comment] 2015-07-10 00:43
@mattbk @rohitpaulk @kzisme @kaguillera @whit537 I can get on IRC to help resolve this in realtime, too. I'm stevepiercy on irc.freenode.net.

**Comment by whit537** [comment] 2015-07-10 11:31
Thanks @stevepiercy. I've stopped using IRC, because it's over-optimized for trolls. You may find others on there, though.

I believe I've confirmed the problem: we don't present *any* UI for removing one's primary email address. Yes? I believe the thinking was that we want to start moving away from social networks for authentication towards email/password for authentication (#1052; because Gratipay deals with money and we therefore shouldn't so heavily lean on people's social network password strength), and so once we have an email for an account we don't want to let it go.

A workaround would be to attach a second email to the account, and set that as primary. I believe we still allow you to remove non-primary emails from an account. Is that a possible workaround for your immediate situations, @ribasushi @stevepiercy?

**Comment by ribasushi** [comment] 2015-07-10 11:47
> we don't present any UI for removing one's primary email address. 

This is... uncool. This means I can not undo the suggested workaround (https://github.com/gratipay/gratipay.com/issues/3587#issuecomment-120393651) and leave the account email-less long-term (it's not clear how long the team account will remain available, given the current limbo...)

**Comment by stevepiercy** [comment] 2015-07-10 12:28
@whit537 I have a primary email account info@knop-project.org for the Team Account on Gratipay for the Knop Project. I have not created a new PayPal account for that address. Is that what you suggest I do?

**Comment by kzisme** [comment] 2015-07-10 12:46
@whit537 When a user authenticates/signs-up/signs-in using a social media outlet it doesn't save their email, correct?  Is there a purpose for a user to choose a specific social media platform to login with then?

I realize that:

>Social accounts are the basis of our anti-fraud.
^ Is this still the way we want to handle things? 

So, I suppose my question now is - do we ~have~ to keep a primary address, or should that be able to be removed/changed/moved to other teams or accounts?  If a user is allowed to remove their primary address - we should just allow them to change their primary address.

**Comment by whit537** [comment] 2015-07-11 02:20
> do we ~have~ to keep a primary address, or should that be able to be removed/changed/moved to other teams or accounts?

I think changed and moved are okay, but I don't think we want to allow having no primary email. In the future I think we want to start requiring a verified email before anyone is able to give or receive money at all. That's already the case for receiving money: team owners need a verified email on file, so that we can communicate with them.

The uncoolness @ribasushi points out is more due to our lack of proper account closing, which I consider our highest development priority right now. We have a PR in review to start bringing that back (#3601), though for @ribasushi we'll also need #3602.

> I have a primary email account info at knop-project dot org for the Team Account on Gratipay for the Knop Project. I have not created a new PayPal account for that address so that it can receive payouts. Is that what you suggest I do?

@stevepiercy Ah, gotcha. We tried contacting you via email about this in [#3567](https://github.com/gratipay/gratipay.com/issues/3567#issuecomment-114330847)—sorry if we missed a reply from you, we're underwater on email support right now. :( (Hoping to catch up on that next week ...)

Short answer: Yes. PayPal is now the only way to withdraw money from Gratipay. Can you make that work on your end?

**Comment by stevepiercy** [comment] 2015-07-11 06:25
@whit537 No, creating a PayPal account for the Team/Project/Company won't work out. That email raised more questions than answered for me, so I filed tickets via FreshDesk.

https://gratipay.freshdesk.com/support/tickets/2427
https://gratipay.freshdesk.com/support/tickets/2531

Anyway, I think I've hijacked this issue, and it would be better to follow up in either my FreshDesk tickets or in #3556.

**Comment by whit537** [comment] 2015-07-11 09:56
> [I]t would be better to follow up in either my FreshDesk tickets or in #3556.

Okay, will do.

**Comment by rohitpaulk** [comment] 2015-07-16 10:15
> If a user is allowed to remove their primary address - we should just allow them to change their primary address.

Just clarifying the current situation here - We don't let users remove their primary email addresses. To change their primary address, one would have to add another email address, verify it and then make it a primary address (After that, they'll be able to delete the old one).

**Comment by mattbk** [comment] 2015-10-19 17:03
Do we require email addresses?  I have seen several accounts where there is no email address listed--perhaps this was lost during the recent redesign and still exists in the database?

**Comment by whit537** [comment] 2015-10-20 20:15
@mattbk No, we don't require an email address. We maybe should, but that depends on #1052.

**Comment by whit537** [comment] 2015-10-20 20:16
Sorry, doesn't really truly depend on.

**Comment by mattbk** [comment] 2015-10-20 20:18
It would be beneficial for #1052 to require an email address.

I only ask because we have no (easy) way to notify people of anything if there is no email address on file.  Social media is great for seeing if people are real, but unless we have a "DM all users across multiple networks with a link to the blog post" feature for admins, getting the word out about changes is difficult.

**Comment by whit537** [comment] 2015-10-20 20:27
> It would be beneficial for #1052 to require an email address.

Reticketed as #3837.

> Just clarifying the current situation here - We don't let users remove their primary email addresses. To change their primary address, one would have to add another email address, verify it and then make it a primary address (After that, they'll be able to delete the old one).

@rohitpaulk Correct. I'm closing this as `wont-fix` (@ribasushi has successfully closed his account).

**Closed by whit537** 2015-10-20 20:27 UTC
Labels: ★★★
