### ISSUE TITLE
Warning in translating "% Funded"

### ISSUE THREAD

**Issue by sidneygijzen** [gratipay/gratipay.com#3175] opened 2015-02-14 18:58 UTC
I was just translating the string "% Funded" into Dutch using the Transifex Web Editor. The string appears at the location ```www/explore/teams/index.spt:39```. I got the following warning:

```Warning: The expression '% F' is not present in the translation.```

A short search resulted in [this Transifex FAQ page](http://docs.transifex.com/faq/#why-is-my-web-editor-complaining-about-the-percentage-sign), which describes some solutions to this problem. I have no clue which solution is preferred, but perhaps there is a policy on that?

**Comment by colindean** [comment] 2015-02-14 19:00
I just ignored it for eo.

**Comment by Changaco** [comment] 2015-02-14 19:01
Closing as duplicate of #2856.

**Closed by Changaco** 2015-02-14 19:01 UTC

**Comment by sidneygijzen** [comment] 2015-02-14 19:06
Thanks for the fast replies guys!
