### ISSUE TITLE
Support for certain causes

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3049] opened 2015-01-03 19:18 UTC
Provide a way to donate for certain things or actions.

You may dislike the person for some thing, so you may still wish to donate for the things that this person does right. There can be also a mechanism for the audience to propose the causes why they want to give money.

For example, if a person is a researcher, it may have a blog, and if there is a way to mark donations as coming for the blog activity, the person may get a better feedback if the work is useful and/or appreciated.

**Comment by Changaco** [comment] 2015-01-03 20:54
Closing as duplicate of #2011 and #222.

**Closed by Changaco** 2015-01-03 20:54 UTC
