### ISSUE TITLE
Fix make schema-diff

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3897] opened 2016-01-20 16:55 UTC
`make schema-diff` errors out when deploying code. It complains about differences between the local and production DB, and all of them are related to payday. This happens because we don't delete all payday related tables and functions in our production DB until the next payday starts. This change was intentional - it helps us debug issues related to payday. I can't find the exact PR where the change was made, if someone does please link it here.

One solution that I see here is to run `payday.sql` against the test DB before generating `local.sql`.

**Comment by whit537** [comment] 2016-01-21 17:19
We could also make the `payday_` tables permanent instead of temporary.

**Comment by whit537** [comment] 2016-03-05 02:49
Dupe of #3471.

**Closed** 2016-03-05 02:49 UTC
Labels: TeamX ★
