### ISSUE TITLE
Allow Persona login

### ISSUE THREAD

**Issue by zilti** [gratipay/gratipay.com#3124] opened 2015-01-16 20:56 UTC
It would be nice to be able to login using Mozilla Persona. That would also automatically include Google- Yahoo- and Hotmail-Login.

**Comment by tshepang** [comment] 2015-01-17 00:31
This is a dupe of https://github.com/gratipay/gratipay.com/issues/756.

**Comment by benhc123** [comment] 2015-01-18 16:09
Changaco said last time:

*"Persona doesn't look like a very good fit for Gratipay, because we already have email addresses for most of our users, but we haven't verified them yet. Persona is designed to verify the email address of a user at sign-up, I doubt that we can do a bulk verification of email addresses we already have, so it's probably going to be simpler for us to implement the traditional email+password authentication.
Closing, feel free to reopen if you disagree."*

**Comment by benhc123** [comment] 2015-01-18 16:12
@zilti, closed. Comment if you disagree. See #756.

**Closed** 2015-01-18 16:11 UTC

**Comment by techtonik** [comment] 2015-02-10 06:56
Persona may be an alternative to email based sign-up. I don't know how of its many users are there, but it definitely simplifies the process for ones who have account there.
