### ISSUE TITLE
Create "complete" user in fake data for development

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3959] opened 2016-03-10 19:04 UTC
This would make it quicker to get up to speed during development if `make fake` is used. 

Probably blocked on https://github.com/gratipay/gratipay.com/issues/3837.

**Comment by aandis** [comment] 2016-03-11 09:33
Duplicate of #3960.

**Closed by aandis** 2016-03-11 09:33 UTC

**Comment by mattbk** [comment] 2016-03-11 15:01
Oops, submission glitch.
