### ISSUE TITLE
include giving due on History page

### ISSUE THREAD

**Issue by YorikSar** [gratipay/gratipay.com#3834] opened 2015-10-18 09:04 UTC
I wandered in to History page and it looked awfully like payments just stopped when I hit 0 balance. I've panicked a bit (are you alive?), read all missed blog posts, understood what the word "arrears" mean, calmed down and then only accidentally found on Giving/Active that everything's find and payments are accumulated there.

I think one should see all payments on History page with payments covered arrears (what a roaring word) having a separate column or smth to link to the charge that covered them. They even can have different color like red while they are not covered (not enough accumulated or stupid me forgot to top up throwaway card I use for Internet payments) and green or normal black when everything's fine with them.
##

**Comment by YorikSar** [comment] 2015-10-18 09:14
By the way, it's also not clear what would happen if you can't charge someone's card for a long time. Will you try to charge more and more as payments accumulate? Will you start "forgetting" older payments?

**Comment by mattbk** [comment] 2015-10-19 14:08
Duplicate of https://github.com/gratipay/gratipay.com/issues/3791 and https://github.com/gratipay/gratipay.com/issues/3612.

**Comment by YorikSar** [comment] 2015-10-19 14:43
I'm sorry, but one of them is about documentation and another one - about Team history. I meant this issue from user perspective only (I'm only giving, not receiving on Gratipay).

**Comment by rohitpaulk** [comment] 2015-10-19 14:52
@YorikSar - Have you had a look at your [giving page](gratipay.com/about/me/giving)? :) We merged https://github.com/gratipay/gratipay.com/pull/3817 recently - you should see the amount due along with how much your current tips are.

**Comment by YorikSar** [comment] 2015-10-19 15:02
@rohitpaulk Yes, I've seen it and that's where I finally found out that everything's fine. But I think it should be seen on History page as well. For me it'd be easier to understand: that week I "spent" this amount, this week I "spent" this amount, and that week I've covered it all with one actual money transfer.

**Comment by whit537** [comment] 2015-11-28 03:06
+1 @dcht00 in https://github.com/gratipay/gratipay.com/issues/3858.

**Closed** 2017-11-02 20:09 UTC
