### ISSUE TITLE
Allow Teams to see who is giving in order to provide extra service

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3883] opened 2015-12-22 21:28 UTC
> Would be nice if project maintainer could determine _reliably_ whether
somebody is a person who is currently giving to the project. So that
maintainer could provide extra support, services, gifts or feature
development.
Is this possible now, or is it something considerable for future?
Thanks.

From https://gratipay.freshdesk.com/helpdesk/tickets/3696.

I assume some sort of fulfillment would need to happen within the system? Or perhaps this is very close to https://github.com/gratipay/gratipay.com/issues/236.

**Comment by whit537** [comment] 2015-12-27 05:08
@rummik asked for something similar a while ago, so this might be a dupe.

I'm pretty sure this goes against the "pay-what-you-want" model that we've been specializing in.

**Comment by mattbk** [comment] 2015-12-28 15:08
I agree, but wanted to add it as a ticket in case others have the same request.

**Comment by jcrben** [comment] 2015-12-29 00:00
@whit537 although it pains me to say this, my impression is that ideological rigidity is getting in the way of providing the value that users expect.

**Comment by whit537** [comment] 2015-12-29 13:41
@jcrben You have jogged my memory. #236 is the issue this is a duplicate of, and #3112 is the PR where we started implementing non-anonymous giving, before getting side-tracked by [Balanced going under](https://medium.com/gratipay-blog/balancedshutdown-3a9fdb32e9c6), the [Gratipocalypse](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8), and [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077). Let's move back over there ...

**Closed by whit537** 2015-12-29 13:41 UTC
