### ISSUE TITLE
Should my team be recieving payments?

### ISSUE THREAD

**Issue by mythmon** [gratipay/gratipay.com#3784] opened 2015-09-14 15:57 UTC
I've been watching gratipay as a possible solution for a community to pay for the costs of a tool (team hamper). So far only one person is signed up to pay the team. I haven't suggested others sign up because so far I haven't seen any payments come through. Is that expected? Is something wrong with my account (~mythmon) or team (hamper) set ups? Or is the site still not up and running?

If the site still isn't transferring payments, or if something is wrong with my account or team, I think there should be big banners that explain that nothing is going to happen.

Our test is a minuscule amount of money, that isn't the issue. It is just a bit off-putting to have the UI say it should be flowing, but then it doesn't.

**Comment by whit537** [comment] 2015-09-14 17:34
Sorry for the trouble, @mythmon. :-(

This sounds like a duplicate of #3756, so I've copied your comments over there with a +1 and am closing this. We need to implement Team history pages in order to debug these issues better: #3612.

**Closed by whit537** 2015-09-14 17:34 UTC
